name: setup_start test and lint

on: push

jobs:

  build:

    runs-on: ubuntu-latest



    steps:

      - uses: action/checkout@v3

      - uses: action/setup-node@v3

      - run: make setup

      - run: make test

      - run: make lint


